n = -3:3;
x = [0, 0, 1, 3, -2, 0, 0];
x_folded = x($:-1:1);
xe = 0.5 * (x + x_folded);
xo = 0.5 * (x - x_folded);
subplot(3, 1, 1);
plot2d3(n, x);
plot(n, x, 'ro');
title("Original Signal x(n)", "fontsize", 4);
xlabel("n", "fontsize", 3);
ylabel("Amplitude", "fontsize", 3);
subplot(3, 1, 2);
plot2d3(n, xe);
plot(n, xe, 'go');
title("Even Signal Component x_e(n)", "fontsize", 4);
xlabel("n", "fontsize", 3);
ylabel("Amplitude", "fontsize", 3);
subplot(3, 1, 3);
plot2d3(n, xo);
plot(n, xo, 'bo');
title("Odd Signal Component x_o(n)", "fontsize", 4);
xlabel("n", "fontsize", 3);
ylabel("Amplitude", "fontsize", 3);
